local M = {}

local cheat_sheet_content = {
  "# Markdown Syntax Reference",
  "",
  "本シートはMarkdownの基本構文をまとめたリファレンスです。",
  "各セクションの [Source] は入力文字、[Output] は描画結果を示します。",
  "",
  "---",
  "",
  "## 1. 見出し (Headings)",
  "",
  "行頭に `#` を記述し、半角スペースを空けます。",
  "見出しの前後には空行を設けることが推奨されます。",
  "",
  "```text",
  "# 見出しレベル1",
  "## 見出しレベル2",
  "### 見出しレベル3",
  "```",
  "",
  "---",
  "",
  "## 2. 改行 (Line Breaks)",
  "",
  "Markdownでは、単純なEnterキーによる改行は無視される場合があります。",
  "明示的な改行を行うには、以下のいずれかの方法を用います。",
  "",
  "```text",
  "1. 行末に半角スペースを2つ記述する  ",
  "2. HTMLの改行タグ <br> を使用する",
  "```",
  "",
  "---",
  "",
  "## 3. リスト (Lists)",
  "",
  "### 箇条書き",
  "行頭に `-` と半角スペースを記述します。",
  "",
  "```text",
  "- 項目A",
  "  - 階層を下げる場合は行頭でTabを押下",
  "  - Tabを連続押下で「→」へ変換",
  "- 項目B",
  "```",
  "",
  "### 番号付きリスト",
  "行頭に数字と `.`、半角スペースを記述します。",
  "",
  "```text",
  "1. 最初のステップ",
  "2. 次のステップ",
  "3. 最後のステップ",
  "```",
  "",
  "---",
  "",
  "## 4. 表 (Tables)",
  "",
  "`|` と `-` を用いて表を構成します。",
  "memo.nvimでは、Tabキーで列間を移動可能です。",
  "",
  "[Source]",
  "```text",
  "| Column L | Column C | Column R |",
  "| :---     | :---:    | ---:     |",
  "| Left     | Center   | Right    |",
  "| 100      | 200      | 300      |",
  "```",
  "",
  "[Output]",
  "| Column L | Column C | Column R |",
  "| :---     | :---:    | ---:     |",
  "| Left     | Center   | Right    |",
  "| 100      | 200      | 300      |",
  "",
  "---",
  "",
  "## 5. 文字装飾 (Text Formatting)",
  "",
  "[Source]",
  "```text",
  "**太字 (Bold)**",
  "*斜体 (Italic)*",
  "~~取り消し線 (Strikethrough)~~",
  "`インラインコード (Inline Code)`",
  "```",
  "",
  "[Output]",
  "**太字 (Bold)**",
  "*斜体 (Italic)*",
  "~~取り消し線 (Strikethrough)~~",
  "`インラインコード (Inline Code)`",
  "",
  "---",
  "",
  "## 6. コードブロック (Code Blocks)",
  "",
  "バッククォート3つで囲むことで、複数行のコードを記述できます。",
  "",
  "[Source]",
  "````text",
  "```python",
  "def main():",
  "    print('Hello World')",
  "```",
  "````",
  "",
  "[Output]",
  "```python",
  "def main():",
  "    print('Hello World')",
  "```",
  "",
  "---",
  "",
  "## 7. 引用とリンク (Quotes & Links)",
  "",
  "### 引用",
  "[Source]",
  "```text",
  "> 引用文の先頭には `>` を付与します。",
  "> 複数行にわたる場合も同様です。",
  "```",
  "",
  "[Output]",
  "> 引用文の先頭には `>` を付与します。",
  "> 複数行にわたる場合も同様です。",
  "",
  "### リンク",
  "[Source]",
  "```text",
  "[表示テキスト](https://example.com)",
  "```",
  "",
  "[Output]",
  "[表示テキスト](https://example.com)",
}

function M.show_help()
  local buf = vim.api.nvim_create_buf(false, true)
  
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, cheat_sheet_content)
  
  vim.cmd("vsplit")
  vim.cmd("wincmd L")
  
  local win = vim.api.nvim_get_current_win()
  vim.api.nvim_win_set_buf(win, buf)
  vim.api.nvim_win_set_width(win, 50)
  
  vim.bo[buf].filetype = "markdown"
  vim.bo[buf].modifiable = false
  vim.bo[buf].bufhidden = "wipe"
  vim.wo[win].spell = false
  
  vim.keymap.set("n", "q", ":q<CR>", { buffer = buf, silent = true, noremap = true })
end

return M
